# Custom Language File for Launcher Customizer

[ejs.app]
title = "MCSquad Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/wally720/mcsquad"
mediaXURL = "https://x.com/mcsquadof"
mediaInstagramURL = "https://instagram.com/mcsquadof/"
mediaYouTubeURL = "#"
mediaDiscordURL = "http://discord.mcsquad.net"

[ejs.settings]
sourceGithubLink = "https://github.com/wally720/MCSquad"
supportLink = "https://github.com/wally720/MCSquad/issues"

[ejs.welcome]
welcomeHeader = "Bienvenido a la MCSquad"
welcomeDescription = "Acá encontraras el acceso a los diferentes proyectos o servidores que tenemos preparados para ti. Estate atento a las actualizaciones y novedades que estaremos anunciando."
welcomeDescCTA = "Estas preparado para la aventura?."